spring:
  application:
    name: microservice-gateway-zuul-filter
  profiles:
    active: z1
server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true



