#spring cloud config认证
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wbppppp/spring-cloud-config-repo

