management:
  port: 8081  #监控端口 spring-boot-actuator
spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix3
server:
  port: 8010
  context-path: /ribbon
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    metadata-map:
      management.port: 8081
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
