server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wbppppp/spring-cloud-config-repo
#rsa非对称加密配置
encrypt:
  keyStore:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
    secret: changeme

