server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wbppppp/spring-cloud-config-repo
  application:
    name: microservice-config-server-eureka
#server注册到eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true


